services:
  edge:
    image: arvindhmanian/quiver-edge:latest
    ports:
      - "8080:8080"
    depends_on:
      - ingest
    container_name: edge-server
    networks:
      - quiver-net
    restart: unless-stopped

  ingest:
    image: arvindhmanian/quiver-ingest:latest
    ports:
      - "1935:1935"
    container_name: ingestion-server
    networks:
      - quiver-net
    restart: unless-stopped

networks:
  quiver-net:
    driver: bridge