apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: edge
  name: edge
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.238.75
  clusterIPs:
  - 34.118.238.75
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 30648
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: edge
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.75.81.163
      ipMode: VIP
