apiVersion: v1
kind: Service
metadata:
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ingestion
  name: ingestion
  namespace: default
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.231.134
  clusterIPs:
  - 34.118.231.134
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31081
    port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app: ingestion
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.74.65.166
      ipMode: VIP
