apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-edge
  labels:
    app: prometheus
spec:
  endpoints:
  - interval: 30s
    port: http
    path: /metrics
  selector:
    matchLabels:
      app: edge