apiVersion: v1
kind: Service
metadata:
  name: ingestion
  labels:
    app: ingestion
spec:
  ports:
  - port: 8080
    name: http
  clusterIP: None
  selector:
    app: ingestion
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ingestion
spec:
  selector:
    matchLabels:
      app: ingestion
  serviceName: "ingestion"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        app: ingestion
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: quiver-ingestion
        image: arvindhmanian/quiver-ingestion:1.0.3
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: ingestion
          mountPath: /mnt/hls
  volumeClaimTemplates:
  - metadata:
      name: ingestion
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi