apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-11-21T06:01:26Z"
  labels:
    app: ingestion
  name: ingestion-pull
  namespace: default
  resourceVersion: "107734"
  uid: a9ded13a-7c13-46c1-b165-eb1d74fcb045
spec:
  clusterIP: 34.118.239.202
  clusterIPs:
  - 34.118.239.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingestion
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
