apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingestion
  name: ingestion-pull
  namespace: default
spec:
  clusterIP: 34.118.239.202
  clusterIPs:
  - 34.118.239.202
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ingestion
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
