apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2024-11-21T05:28:48Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  labels:
    app: ingestion
  name: ingestion
  namespace: default
  resourceVersion: "78182"
  uid: c6b8f27b-12d7-47d7-b514-06de8ace20a0
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 34.118.231.134
  clusterIPs:
  - 34.118.231.134
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 31081
    port: 1935
    protocol: TCP
    targetPort: 1935
  selector:
    app: ingestion
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.74.65.166
      ipMode: VIP
