name: Push Docker Images

on:
  release:
    types:
      - published

jobs:
  build-and-push-edge:
    name: Build and Push Edge Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Edge Docker Image
        uses: docker/build-push-action@v4
        with:
          context: ./edge
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/quiver-edge:latest
            ${{ secrets.DOCKER_USERNAME }}/quiver-edge:${{ github.event.release.tag_name }}
       
  build-and-push-ingestion:
    name: Build and Push Ingestion Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Quiver Ingestion Image
        uses: docker/build-push-action@v4
        with:
          context: ./ingestion
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/quiver-ingestion:latest
            ${{ secrets.DOCKER_USERNAME }}/quiver-ingestion:${{ github.event.release.tag_name }}
  
  build-and-push-ingestion-external:
    name: Build and Push Ingestion External Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Quiver Ingestion External Image
        uses: docker/build-push-action@v4
        with:
          context: ./ingestion-external
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/quiver-ingestion-external:latest
            ${{ secrets.DOCKER_USERNAME }}/quiver-ingestion-external:${{ github.event.release.tag_name }}